language: node_js
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      node_js: "6"
    - os: osx
      osx_image: xcode7.3
      node_js: "6"
before_install:
  - ./.travis/setup.sh
