language: node_js
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      node_js:
        - "4"
        - "5"
        - "6"
        - "7"
    - os: osx
      osx_image: xcode8.2
      node_js:
        - "4"
        - "5"
        - "6"
        - "7"
before_install:
  - ./.travis/setup.sh
