language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.2
before_install:
  - ./.travis/setup.sh
